### ISSUE TITLE
[Sprint 3] - [Homepage] - Sayfanın Geneliyle İlgili Hatalar 

### ISSUE THREAD

**Issue by ummugulsumm** [bimser-intern/surveysaurus-pm#105]
**Sayfanın Geneli**

- [ ] Sayfadaki yazı stili tasarımdakinden farklı gözükmektedir. (Aynı font-family olsa dâhi.)
- [x] Sayfanın arka plan görüntüsü tasarımla örtüşmemektedir. Tasarımdaki renkli daireler sayıca daha fazla ve farklı farklı renklerdedir. Ayrıca eklenen daire fotoğraflarının kalitesi de oldukça düşük gözükmektedir. Arka plandaki renklendirmenin de tasarımla aynı olması beklenmektedir.
- [ ] Büyük başlığın sağ alt kısmında bulunan "Create Your Surveys" yazısının kenarları #000000 renk kodunda olmalıdır. 
- [x] Başlıkların arka plan resminin kenarları sol üst köşede fazla belirgin gözükmektedir. Onun daha transparan olması gerekmektedir.
- [x] Ana sayfada scrolla aşağıya indiğimizde Home yazısına tıkladığımızda çalışmamaktadır. Home yazısına tıkladığımızda üst kısma geri dönmemiz gerekmektedir. 

**Anket Oluşturma Butonu**

- [x]  Buton tasarımdaki gibi biraz daha büyük ve bir miktar daha aşağıda olmalıdır.

**Üst Bar**

- [x] Sayfalar arasında geçişlerde üst barın genişliğinin farklılığı belli olmaktadır. Tüm sayfalardaki üst bar aynı genişliğe sahip olmalıdır. 
- [x] Sayfa scroll edildiğinde üst barın arka planı sabit kalmamaktadır. Sayfadaki diğer görüntüler sayfa scroll edildikçe üst barın arka planı olarak gözükmektedir. Üst barın arka planının da sabit kalması gerekmektedir.

 **Sayfanın Alt Kısmı**

- [x] "Create A Survey" yazısının altında kalan butonun kalınlığı tasarımdakine uygun olmalıdır. Daha ince olması gerekmektedir. Ayrıca butonun arka planının renk kodu #5380EA şeklinde olmalıdır.   

**Anketlerin Listelendiği Bölüm**

- [x] Üst bardan Surveys kısmına tıklandığında başlık (Our Sample Surveys)  görünecek şekilde -tasarımdaki gibi- ekrana gelmesi beklenmektedir. Şu an geliyor gibi gözükse de üst bardaki sorun ortadan kaldırıldığında ve üst barın arka planı sabit kaldığında başlık gözükmeyecektir.  About Us kısmı içinde aynı durum söz konusudur. 
- [x] "Our Sample Surveys" yazısının renk kodu  #000000 şeklinde olmalıdır.  
- [x] Başlığın altında bulunan anketlerin görüntü düzeni tasarımla uyuşmamaktadır. Sorular ve resimler arasında bir satır daha mesafe olmalıdır. Anketler arasında çizgilerin şekli tasarımdakiyle uyuşmamaktadır. Tasarıma bakılması gerekiyor. Resimlerin üstünden bir çizgi geçmektedir ve bunun olmaması beklenmektedir. Anketlerin arasındaki çizgiler tasarımdakinden kalın gözükmektedir ve iki anket arasında olan kısa boşluk mevcut değildir. Tasarıma göre güncellenmesi beklenmektedir.
- [x] Kenardaki oklar tasarıma uygun değildir. Şekil ve renkleri, anket kısmına uzaklıkları tasarımdaki gibi olmalıdır. Anketlerin alt kısmında bulunan daireler de tasarımdakinden farklıdır. Renk ve boyut olarak tasarımdakine uygun olmalıdır.
- [x] Arka planda kalan ok işareti arka plandan çıkarılmalıdır.
