### ISSUE TITLE
[HomePage]-Başlangıç Sayfasında Başlangıç Metni, Üst bar ve Anket Oluşturma Butonunun Düzenlenmesi

### ISSUE THREAD

**Issue by oykumotor** [bimser-intern/surveysaurus-pm#17]
Başlangıç Metni
------------------
- [x]  Sayfada karşılama metni olarak "Surveysaurus" yazısı yazılmalıdır. Bu yazı #5380EA renk kodunda olmalıdır. 

 - [x]  Karşılama metninin sağ altında  "Create Your Surveysaurus For Free" yazmalıdır.  "Create Your Surveysaurus For Free" yazısı #F27E97 renk koduna sahip olmalıdır. Yazının kenarları #000000 renk kodunda olmalıdır.

- [x]  Üst maddelerdeki yazıların hepsi ana sayfanın merkezinde ve birbirleriyle orantılı olacak şekilde ayarlanmalıdır.

Anket Oluşturma Butonu
---------------------------
- [x] Ana sayfada "Create A Survey" butonu olmalı ve bu buton anket oluşturma sayfasına yönlendirmelidir.

- [x]  İmleç "Create A Survey" butonunun üzerine getirildiğinde buton belirginleşmelidir. Yani bir miktar büyümelidir.

- [x] "Create A Survey" butonu #93ABE2 renk koduna sahip olmalıdır. Buton kenarları %40 oval olmalıdır. Butonun arka planı #F6FBF8 renk kodunda olmalıdır. 
 

Üst Bar
----------

- [x]  Üst barın orta kısmında logo bulunmalıdır.

- [x]  Scroll yapıldığında üst bar sabit kalmalı ve görünmeye devam etmelidir.

- [x]  Üst barın sağ tarafında "Sign Up" ve "Login" butonları bulunmalıdır.  "Sign Up" ve "Login" butonlarının en sağında ikon yer almalıdır.

- [x]  Üst barın en sağ kısmında ikon, onun solunda "Login" ve onun da solunda da "Sign Up" yazısı yer almalıdır.
Yazıların renk kodu #000000, "Sign Up" butonu renk kodu #F0B80D ve "Login" butonunun renk kodu #F27E97 şeklinde olmalıdır.

- [x] Üst barın en sol kısmında "Home", onun sağında "About" ve onun sağında da "Surveys" yazısı yer almalıdır.

**Comment by ummugulsumm** [comment]
## Test Senaryosu

### Başlangıç sayfasında başlangıç metninin düzeni

- **Test Adımları**

1. Karşılama metin içeriği ve rengi kontrol edilmelidir.                     
2. Sağ alt kısımda yazan yazının içeriği ve rengi kontrol edilmelidir.      
3. Sayfa düzeni kontrol edilmelidir.

- **Beklenen Sonuç**

1. "Surveysaurus" yazısı yazılmalıdır. #5380EA renk kodunda olmalıdır.                         
2. "Create Your Surveysaurus For Free" yazmalıdır. Yazı, #F27E97 renk kodunda; yazının kenarları #000000 renk kodunda olmalıdır.                                                             
3. Yazıların hepsi ana sayfanın merkezinde ve birbirleriyle orantılı olacak şekilde ayarlanmalıdır.

### Başlangıç sayfasında anket oluşturma butonunun düzeni

- **Test Adımları**

1. Butonun özellikleri ve içeriği kontrol edilmelidir.                    
2. İmleç butonun üzerine getirilmelidir.    
3. Butona basılmalıdır.

- **Beklenen Sonuç**

1. İçinde "Create A Survey" yazmalı ve #93ABE2 renk kodunda olmalıdır. Buton arka planı #F6FBF8 renk kodunda ve buton kenarları %40 oval olmalıdır.                   
2. Buton belirginleşmeli ve bir miktar büyümelidir.                                               
3. Anket oluşturma sayfasına yönlendirmelidir.

### Başlangıç sayfasında üst barın düzeni

- **Test Adımları**

1. Üst barın düzeni, yazılar, butonlar ve renkleri kontrol edilmelidir.                      
2. Sayfa scroll edilmelidir.

- **Beklenen Sonuç**

1. Üst barın orta kısmında logo,en sağ kısmında ikon, onun solunda "Login" ve onun da solunda da "Sign Up" yazısı yer almalıdır. Yazıların renk kodu #000000, "Sign Up" butonu renk kodu #F0B80D ve "Login" butonunun renk kodu #F27E97 şeklinde olmalıdır. En sol kısmında "Home", onun sağında "About" ve onun sağında da "Surveys" yazısı yer almalıdır.                       
2. Üst bar sabit kalmalıdır ve görünmeye devam etmelidir.
